# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 512b30bd20967f4c53efbe926c12d25c56b039e1f7ce9920b113a58c44bb360e4e16cdcf4500c5217807dfd3623adba24906dab9dadcef410ba18986d1321daf

test:
  secret_key_base: aa031188c86524af51ac31928e9d6c912dddc45aa8a63129752b3e1eec18b49f3a7e080ee82661371564c4e98c302248abefd32fc64f32a4bab68eb5decb2ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
